### ISSUE TITLE
Formatage des fichiers csv

### ISSUE THREAD

**Issue by Squ8re** [l9kd1/LINFO-1341-HAR-extractor#2]
Hello !
Merci pour ton travail vraiment génial :)
En le réutilisant, je me suis rappelé que je reformatais à chaque fois les csv exportés parce que toutes les infos se mettent dans la première colonne (il y a des virgules au lieu des points virgules dans ce code).

Je ne sais pas si tu pourrais facilement remplacer ton formatage en virgule par point virgule ni si ce qui suit sera utile ici mais voici toujours la façon dont je procède : 

``` { python }
def lecteur(filename, separateur=None):
    # lecture des données
    with codecs.open(filename, 'r', 'utf-8') as f:
        donnees = f.readlines()

    donnees = [x.strip() for x in donnees]  # suppression des \n

    # Séparation des données
    # ------------------------------------------------------------------------
    if separateur:
        donnees = [x.split(separateur) for x in donnees]
    return donnees

def formatage(nomDeFichier):
    file = lecteur("Analyse http/"+nomDeFichier, separateur =',')
    
    with open("Analyse http/Format/"+nomDeFichier, 'w') as f:
        for ligne in file:
            string = ""
            for element in ligne:
                string += (element + ";")
                
            f.write(string+'\n')
```

Ce code est super basique et ne sert qu'à remplacer les virgules par des points virgules... 😄 

Merci pour ton fabuleux travail !

**Comment by l9kd1** [comment]
Hello !
Normalement tu peux choisir le séparateur lorsque tu ouvres le .csv dans Libre Office 
![Capture d’écran 2021-05-10 234649](https://user-images.githubusercontent.com/79046800/117728904-5ca96100-b1ea-11eb-8fa6-97cec27a77b7.png)

ou dans Excel.
[https://support.affinity.co/hc/en-us/articles/360044453711-How-to-open-CSV-files-with-the-correct-delimiter-separator](https://support.affinity.co/hc/en-us/articles/360044453711-How-to-open-CSV-files-with-the-correct-delimiter-separator)

Je vais toutefois mettre un lien vers cette issue dans le readme pour que tout le monde puisse profiter de ton script. 👍 

Merci pour ton retour en tout cas !

**Comment by Squ8re** [comment]
Génial, j'apprends des nouvelles choses :)

(Mon prénom c'est Amadéo d'ailleurs haha)
